SELECT
    DISTINCT *,
    MIN(KC_STATUS) OVER (PARTITION BY CLAIMID_1 ) AS KEEP_CLAIM, 
FROM
    (
  SELECT DISTINCT *,
        LAG(SUM_ENDRES, 1, 0) OVER (PARTITION BY CLAIMID_1 ORDER BY CLAIMID_1, RE_BALANCEYEARPTF) AS SUM_PREV_ENDRES,
        IF (COALESCE(SUM_BEGRES, 0)=LAG
(SUM_ENDRES, 1, 0) OVER
(PARTITION BY CLAIMID_1 ORDER BY CLAIMID_1, RE_BALANCEYEARPTF) , 'KEEP CLAIM', 'K.O') AS KC_STATUS,
  FROM
(
  SELECT DISTINCT
    CLAIMID_1,
    LOCALINSURER,
    RE_BALANCEYEARPTF,
    COALESCE(SUM(BEGRES) OVER (PARTITION BY CLAIMID_1, RE_BALANCEYEARPTF ORDER BY CLAIMID_1, RE_BALANCEYEARPTF ),0) AS SUM_BEGRES,--not MAX, CONFIRMED
    COALESCE(SUM(ENDRES) OVER (PARTITION BY CLAIMID_1, RE_BALANCEYEARPTF ORDER BY CLAIMID_1, RE_BALANCEYEARPTF ),0) AS SUM_ENDRES, --not MIN, CONFIRMED

FROM
    `geb
-dwh-test.uat_geb_dwh_eu_act.fact_actuary_staging`
    -- ORDER BY CLAIMID_1, RE_BALANCEYEARPTF
  ) s
)
  -- ORDER BY CLAIMID_1, RE_BALANCEYEARPTF