WITH
    non_cum
    as
    
    (
        SELECT DISTINCT *
        FROM(
   SELECT DISTINCT * EXCEPT(SUM_PAID
    ),
SUM(SUM_PAID) OVER
(PARTITION BY AY_ACCIDENT_YEAR,COVERCODE_NEW , PO_LINEOFRISK ORDER BY AY_ACCIDENT_YEAR,DEVELOPMENT_PERIOD_ON_AY ROWS BETWEEN UNBOUNDED PRECEDING  AND CURRENT ROW) AS CUM_PAID
FROM
(

  SELECT
    DISTINCT PO_LINEOFRISK,
    COVERCODE_NEW,
    AY_ACCIDENT_YEAR,
    DEVELOPMENT_PERIOD_ON_AY,
    SUM(PAID) OVER (PARTITION BY AY_ACCIDENT_YEAR,DEVELOPMENT_PERIOD_ON_AY, PO_LINEOFRISK, COVERCODE_NEW ORDER BY AY_ACCIDENT_YEAR,DEVELOPMENT_PERIOD_ON_AY ) SUM_PAID
FROM
    `geb
-dwh-test.uat_geb_dwh_eu_act.db_run_off_fields` a
WHERE
  COVERCODE_NEW IN
('LTD','PD','LTD-SS') AND 
  CAST
(a.AY_ACCIDENT_YEAR AS INT64 )>=2012 --TBC
)
      ) PIVOT
(MAX
(CUM_PAID) CUM_PAID FOR DEVELOPMENT_PERIOD_ON_AY IN
(0,1,2,3,4,5,6,7,8)) 
  
      )
--Below, SUM_PAID is only for testing, will be removed before production run
SELECT DISTINCT * , 

FROM non_cum
ORDER BY
  COVERCODE_NEW,  AY_ACCIDENT_YEAR

