DECLARE i INT64;
DECLARE ARR ARRAY<STRUCT<LOCALINSURER STRING, BALANCE_YEAR INT64, QUARTER STRING, COVER_CODE STRING>>;

SET i
=
(SELECT FORMAT("%T", ARRAY_AGG(x)) AS array_concat_agg
FROM (SELECT DISTINCT LOCALINSURER, BALANCE_YEAR, QUARTER, COVER_CODE
    FROM `geb-dwh
-test.uat_geb_dwh_eu_act.prophet_input` 
ORDER BY LOCALINSURER, BALANCE_YEAR, QUARTER, COVER_CODE) AS x);

WHILE i >0 DO
SELECT *
FROM `geb
-dwh-test.uat_geb_dwh_eu_act.prophet_input`
  WHERE LOCALINSURER = ARR[ORDINAL(i)].LOCALINSURER AND BALANCE_YEAR=ARR[ORDINAL(i)].BALANCE_YEAR AND QUARTER=ARR[ORDINAL(i)].QUARTER AND COVER_CODE=ARR[ORDINAL(i)].COVER_CODE;
SET i
=i-1;
END
WHILE;
