# You are given two strings s and t. String t is generated by randomly
# shuffling string s and then adding one more letter at a random position.
# Return the letter that was added to t.


def find_the_difference(s, t):
    return chr(sum(map(ord, t))-sum(map(ord, s)))


find_the_difference("abcd", "abcde")  # "e"

find_the_difference("", "y")  # "y"

find_the_difference("ae", "aea")  # "a"


def find_the_difference1(s, t):
    return [i for i in t if t.count(i) != s.count(i)][0]
